name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - name: View context attributes
      - uses: actions/github-script@v6
        with:
          script: console.log("testing123", context)
