
# When issues are added to this repo they will automatically get classified by label and added to various project boards
name: "Issue to Project Board Automation"
on:
  workflow_dispatch:
  issues:
    types: [opened, labeled]
jobs:
  categorize_project_issues:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
    - name: 'Add to "pe-actions-runtime" "Needs Triage"'
      uses: konradpabjan/actions-add-new-issue-to-column@v1.1
      if: contains(github.event.issue.labels.*.name, 'compute-runtime')
      with:
        action-token: ${{ secrets.PROJECT_TOKEN }}
        project-url: "https://github.com/orgs/github/projects/7807"
        column-name: "Needs Triage"
