
# When issues are added to this repo they will automatically get classified by label and added to various project boards
name: "Issue to Project Board Automation"
on:
  workflow_dispatch:
  issues:
    types: [opened, labeled]
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:

          project-url: https://github.com/orgs/github/projects/7807
          github-token: ${{ secrets.PROJECT_TOKEN }}
          labeled: compute-runtime
          label-operator: OR
  
