name: 'Generate Standup Order Test'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * 2,3,4'

jobs:
  standup-order:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: luketomlinson/standup-order@main
        with:
          prepend-message: "Today's ARC standup driver is:"
          number-of-people: 1
          icon-emoji: ':car:'
          slack-channel: benwells-test-channel-public
          team-members: tingluohuang,fhammerl,avastancu,cory-miller,link-,rentziass,vanzeben
          slack-webhook-url: ${{ secrets.STANDUP_ORDER_SLACK_WEBHOOK }}
      
